spring:
  application:
    name: yapily-paycli
  main:
    web-application-type: none
    banner-mode: off
  shell:
    enabled: true
    interactive:
      enabled: true
    noninteractive:
      enabled: false
    history:
      enabled: true
    command:
      version:
        enabled: true

cli:
  login:
    url: https://yapily.com
  configuration:
    path: ${YAPILY_CONFIG_HOME:${user.home}/.config/yapilycli}
    file: config.toml


#logging:
#  level:
#    root: INFO
#    org.springframework.shell: DEBUG
#    platform.application: DEBUG